import humanfriendly
import radical.utils as ru

from socm.core import Resource, Workflow
from socm.planner import HeftPlanner

try:
    import mock
except ImportError:
    from unittest import mock


# ------------------------------------------------------------------------------
#
@mock.patch.object(HeftPlanner, "__init__", return_value=None)
def test_plan(mocked_init):
    # Create Workflow objects for the campaign
    workflows = [
        Workflow(
            name=f"W{i+1}", executable="exe", context="ctx", subcommand="sub", id=i + 1
        )
        for i in range(10)
    ]
    # Map workflow names to objects for easy lookup
    {wf.name: wf for wf in workflows}

    actual_plan = [
        (
            Workflow(
                name="W1",
                executable="exe",
                context="ctx",
                subcommand="sub",
                id=1,
                environment=None,
                resources=None,
            ),
            range(64, 128),
            2000,
            0,
            45,
        ),
        (
            Workflow(
                name="W2",
                executable="exe",
                context="ctx",
                subcommand="sub",
                id=2,
                environment=None,
                resources=None,
            ),
            range(128, 144),
            15000,
            0,
            25,
        ),
        (
            Workflow(
                name="W3",
                executable="exe",
                context="ctx",
                subcommand="sub",
                id=3,
                environment=None,
                resources=None,
            ),
            range(0, 1),
            2000,
            0,
            560,
        ),
        (
            Workflow(
                name="W4",
                executable="exe",
                context="ctx",
                subcommand="sub",
                id=4,
                environment=None,
                resources=None,
            ),
            range(16, 24),
            32000,
            0,
            140,
        ),
        (
            Workflow(
                name="W5",
                executable="exe",
                context="ctx",
                subcommand="sub",
                id=5,
                environment=None,
                resources=None,
            ),
            range(8, 16),
            1000,
            0,
            145,
        ),
        (
            Workflow(
                name="W6",
                executable="exe",
                context="ctx",
                subcommand="sub",
                id=6,
                environment=None,
                resources=None,
            ),
            range(112, 224),
            20000,
            45,
            55,
        ),
        (
            Workflow(
                name="W7",
                executable="exe",
                context="ctx",
                subcommand="sub",
                id=7,
                environment=None,
                resources=None,
            ),
            range(168, 224),
            6000,
            0,
            20,
        ),
        (
            Workflow(
                name="W8",
                executable="exe",
                context="ctx",
                subcommand="sub",
                id=8,
                environment=None,
                resources=None,
            ),
            range(32, 64),
            1000,
            0,
            30,
        ),
    ]
    planner = HeftPlanner(None, None, None)
    planner._logger = ru.Logger("dummy")
    planner._est_memory = list()

    planner._resource_requirements = {
        "W1": {"req_walltime": 45, "req_cpus": 64, "req_memory": 2000},
        "W2": {"req_walltime": 25, "req_cpus": 16, "req_memory": 15000},
        "W3": {"req_walltime": 560, "req_cpus": 1, "req_memory": 2000},
        "W4": {"req_walltime": 140, "req_cpus": 8, "req_memory": 32000},
        "W5": {"req_walltime": 145, "req_cpus": 8, "req_memory": 1000},
        "W6": {"req_walltime": 10, "req_cpus": 112, "req_memory": 20000},
        "W7": {"req_walltime": 20, "req_cpus": 56, "req_memory": 6000},
        "W8": {"req_walltime": 30, "req_cpus": 32, "req_memory": 1000},
    }

    planner._campaign = workflows
    planner._resources = Resource(
        name="tiger3",
        nodes=2,
        cores_per_node=112,
        memory_per_node=64 * 1024,  # in MB
        default_queue="normal",
        maximum_walltime=1440,  # in minutes
    )
    planner._num_oper = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    est_plan, _ = planner.plan()

    assert est_plan == actual_plan


@mock.patch.object(HeftPlanner, "__init__", return_value=None)
def test_failing_plan(mocked_init):
    workflows = [
        Workflow(
            name="ml_mapmaking_workflow",
            executable="so-site-pipeline",
            context="file:///context.yaml",
            subcommand="make-ml-map",
            id=1,
            environment={},
            resources={
                "ranks": 896,
                "threads": 8,
                "memory": 64000000,
                "runtime": 12000,
            },
            area="file:///geometry.fits",
            output_dir="/output",
            query="file://obslist_balanced.txt",
            datasize=5230991388,
            comps="TQU",
            wafers=None,
            bands="f090",
            nmat="corr",
            max_dets=None,
            site="act",
            downsample=1,
            maxiter=100,
            tiled=1,
            wafer="ws0",
        ),
        Workflow(
            name="mission_split_1_null_test_workflow",
            executable="so-site-pipeline",
            context="file:///context.yaml",
            subcommand="make-ml-map",
            id=2,
            environment={},
            resources={
                "ranks": 224,
                "threads": 8,
                "memory": 16000000,
                "runtime": 12000,
            },
            area="file:///geometry.fits",
            output_dir="/mission_split_1",
            query="file://query.txt",
            datasize=1311130012,
            comps="TQU",
            wafers=None,
            bands="f090",
            nmat="corr",
            max_dets=None,
            site="act",
            downsample=1,
            maxiter=100,
            tiled=1,
            chunk_nobs=1,
            chunk_duration=None,
            nsplits=4,
            wafer="ws0",
        ),
        Workflow(
            name="mission_split_2_null_test_workflow",
            executable="so-site-pipeline",
            context="file:///context.yaml",
            subcommand="make-ml-map",
            id=3,
            environment={},
            resources={
                "ranks": 224,
                "threads": 8,
                "memory": 16000000,
                "runtime": 12000,
            },
            area="file:///geometry.fits",
            output_dir="/mission_split_2",
            query="file://query.txt",
            datasize=1307133118,
            comps="TQU",
            wafers=None,
            bands="f090",
            nmat="corr",
            max_dets=None,
            site="act",
            downsample=1,
            maxiter=100,
            tiled=1,
            chunk_nobs=1,
            chunk_duration=None,
            nsplits=4,
            wafer="ws0",
        ),
        Workflow(
            name="mission_split_3_null_test_workflow",
            executable="so-site-pipeline",
            context="file:///context.yaml",
            subcommand="make-ml-map",
            id=4,
            environment={},
            resources={
                "ranks": 224,
                "threads": 8,
                "memory": 16000000,
                "runtime": 12000,
            },
            area="file:///geometry.fits",
            output_dir="/mission_split_3",
            query="file://query.txt",
            datasize=1305106812,
            comps="TQU",
            wafers=None,
            bands="f090",
            nmat="corr",
            max_dets=None,
            site="act",
            downsample=1,
            maxiter=100,
            tiled=1,
            chunk_nobs=1,
            chunk_duration=None,
            nsplits=4,
            wafer="ws0",
        ),
        Workflow(
            name="mission_split_4_null_test_workflow",
            executable="so-site-pipeline",
            context="file:///context.yaml",
            subcommand="make-ml-map",
            id=5,
            environment={},
            resources={
                "ranks": 224,
                "threads": 8,
                "memory": 16000000,
                "runtime": 12000,
            },
            area="file:///geometry.fits",
            output_dir="/mission_split_4",
            query="file://query.txt",
            datasize=1307621446,
            comps="TQU",
            wafers=None,
            bands="f090",
            nmat="corr",
            max_dets=None,
            site="act",
            downsample=1,
            maxiter=100,
            tiled=1,
            chunk_nobs=1,
            chunk_duration=None,
            nsplits=4,
            wafer="ws0",
        ),
        Workflow(
            name="wafer_ws0_split_1_null_test_workflow",
            executable="so-site-pipeline",
            context="file:///context.yaml",
            subcommand="make-ml-map",
            id=6,
            environment={},
            resources={
                "ranks": 224,
                "threads": 8,
                "memory": 16000000,
                "runtime": 12000,
            },
            area="file:///geometry.fits",
            output_dir="/wafer_ws0_split_1",
            query="file://query.txt",
            datasize=1311130012,
            comps="TQU",
            wafers=None,
            bands="f090",
            nmat="corr",
            max_dets=None,
            site="act",
            downsample=1,
            maxiter=100,
            tiled=1,
            chunk_nobs=1,
            chunk_duration=None,
            nsplits=4,
            wafer="ws0",
        ),
        Workflow(
            name="wafer_ws0_split_2_null_test_workflow",
            executable="so-site-pipeline",
            context="file:///context.yaml",
            subcommand="make-ml-map",
            id=7,
            environment={},
            resources={
                "ranks": 224,
                "threads": 8,
                "memory": 16000000,
                "runtime": 12000,
            },
            area="file:///geometry.fits",
            output_dir="/wafer_ws0_split_2",
            query="file://query.txt",
            datasize=1307133118,
            comps="TQU",
            wafers=None,
            bands="f090",
            nmat="corr",
            max_dets=None,
            site="act",
            downsample=1,
            maxiter=100,
            tiled=1,
            chunk_nobs=1,
            chunk_duration=None,
            nsplits=4,
            wafer="ws0",
        ),
        Workflow(
            name="wafer_ws0_split_3_null_test_workflow",
            executable="so-site-pipeline",
            context="file:///context.yaml",
            subcommand="make-ml-map",
            id=8,
            environment={},
            resources={
                "ranks": 224,
                "threads": 8,
                "memory": 16000000,
                "runtime": 12000,
            },
            area="file:///geometry.fits",
            output_dir="/wafer_ws0_split_3",
            query="file://query.txt",
            datasize=1305106812,
            comps="TQU",
            wafers=None,
            bands="f090",
            nmat="corr",
            max_dets=None,
            site="act",
            downsample=1,
            maxiter=100,
            tiled=1,
            chunk_nobs=1,
            chunk_duration=None,
            nsplits=4,
            wafer="ws0",
        ),
        Workflow(
            name="wafer_ws0_split_4_null_test_workflow",
            executable="so-site-pipeline",
            context="file:///context.yaml",
            subcommand="make-ml-map",
            id=9,
            environment={},
            resources={
                "ranks": 224,
                "threads": 8,
                "memory": 16000000,
                "runtime": 12000,
            },
            area="file:///geometry.fits",
            output_dir="/wafer_ws0_split_4",
            query="file://query.txt",
            datasize=1307621446,
            comps="TQU",
            wafers=None,
            bands="f090",
            nmat="corr",
            max_dets=None,
            site="act",
            downsample=1,
            maxiter=100,
            tiled=1,
            chunk_nobs=1,
            chunk_duration=None,
            nsplits=4,
            wafer="ws0",
        ),
        Workflow(
            name="direction_rising_split_1_null_test_workflow",
            executable="so-site-pipeline",
            context="file:///context.yaml",
            subcommand="make-ml-map",
            id=10,
            environment={},
            resources={
                "ranks": 224,
                "threads": 8,
                "memory": 16000000,
                "runtime": 12000,
            },
            area="file:///geometry.fits",
            output_dir="/direction_rising_split_1",
            query="file://query.txt",
            datasize=691266434,
            comps="TQU",
            wafers=None,
            bands="f090",
            nmat="corr",
            max_dets=None,
            site="act",
            downsample=1,
            maxiter=100,
            tiled=1,
            chunk_nobs=1,
            chunk_duration=None,
            nsplits=4,
            wafer="ws0",
        ),
        Workflow(
            name="direction_rising_split_2_null_test_workflow",
            executable="so-site-pipeline",
            context="file:///context.yaml",
            subcommand="make-ml-map",
            id=11,
            environment={},
            resources={
                "ranks": 224,
                "threads": 8,
                "memory": 16000000,
                "runtime": 12000,
            },
            area="file:///geometry.fits",
            output_dir="/direction_rising_split_2",
            query="file://query.txt",
            datasize=689067348,
            comps="TQU",
            wafers=None,
            bands="f090",
            nmat="corr",
            max_dets=None,
            site="act",
            downsample=1,
            maxiter=100,
            tiled=1,
            chunk_nobs=1,
            chunk_duration=None,
            nsplits=4,
            wafer="ws0",
        ),
        Workflow(
            name="direction_rising_split_3_null_test_workflow",
            executable="so-site-pipeline",
            context="file:///context.yaml",
            subcommand="make-ml-map",
            id=12,
            environment={},
            resources={
                "ranks": 224,
                "threads": 8,
                "memory": 16000000,
                "runtime": 12000,
            },
            area="file:///geometry.fits",
            output_dir="/direction_rising_split_3",
            query="file://query.txt",
            datasize=689196634,
            comps="TQU",
            wafers=None,
            bands="f090",
            nmat="corr",
            max_dets=None,
            site="act",
            downsample=1,
            maxiter=100,
            tiled=1,
            chunk_nobs=1,
            chunk_duration=None,
            nsplits=4,
            wafer="ws0",
        ),
        Workflow(
            name="direction_rising_split_4_null_test_workflow",
            executable="so-site-pipeline",
            context="file:///context.yaml",
            subcommand="make-ml-map",
            id=13,
            environment={},
            resources={
                "ranks": 224,
                "threads": 8,
                "memory": 16000000,
                "runtime": 12000,
            },
            area="file:///geometry.fits",
            output_dir="/direction_rising_split_4",
            query="file://query.txt",
            datasize=689290508,
            comps="TQU",
            wafers=None,
            bands="f090",
            nmat="corr",
            max_dets=None,
            site="act",
            downsample=1,
            maxiter=100,
            tiled=1,
            chunk_nobs=1,
            chunk_duration=None,
            nsplits=4,
            wafer="ws0",
        ),
        Workflow(
            name="direction_setting_split_1_null_test_workflow",
            executable="so-site-pipeline",
            context="file:///context.yaml",
            subcommand="make-ml-map",
            id=14,
            environment={},
            resources={
                "ranks": 224,
                "threads": 8,
                "memory": 16000000,
                "runtime": 12000,
            },
            area="file:///geometry.fits",
            output_dir="/direction_setting_split_1",
            query="file://query.txt",
            datasize=615677782,
            comps="TQU",
            wafers=None,
            bands="f090",
            nmat="corr",
            max_dets=None,
            site="act",
            downsample=1,
            maxiter=100,
            tiled=1,
            chunk_nobs=1,
            chunk_duration=None,
            nsplits=4,
            wafer="ws0",
        ),
        Workflow(
            name="direction_setting_split_2_null_test_workflow",
            executable="so-site-pipeline",
            context="file:///context.yaml",
            subcommand="make-ml-map",
            id=15,
            environment={},
            resources={
                "ranks": 224,
                "threads": 8,
                "memory": 16000000,
                "runtime": 12000,
            },
            area="file:///geometry.fits",
            output_dir="/direction_setting_split_2",
            query="file://query.txt",
            datasize=621404494,
            comps="TQU",
            wafers=None,
            bands="f090",
            nmat="corr",
            max_dets=None,
            site="act",
            downsample=1,
            maxiter=100,
            tiled=1,
            chunk_nobs=1,
            chunk_duration=None,
            nsplits=4,
            wafer="ws0",
        ),
        Workflow(
            name="direction_setting_split_3_null_test_workflow",
            executable="so-site-pipeline",
            context="file:///context.yaml",
            subcommand="make-ml-map",
            id=16,
            environment={},
            resources={
                "ranks": 224,
                "threads": 8,
                "memory": 16000000,
                "runtime": 12000,
            },
            area="file:///geometry.fits",
            output_dir="/direction_setting_split_3",
            query="file://query.txt",
            datasize=618468316,
            comps="TQU",
            wafers=None,
            bands="f090",
            nmat="corr",
            max_dets=None,
            site="act",
            downsample=1,
            maxiter=100,
            tiled=1,
            chunk_nobs=1,
            chunk_duration=None,
            nsplits=4,
            wafer="ws0",
        ),
        Workflow(
            name="direction_setting_split_4_null_test_workflow",
            executable="so-site-pipeline",
            context="file:///context.yaml",
            subcommand="make-ml-map",
            id=17,
            environment={},
            resources={
                "ranks": 224,
                "threads": 8,
                "memory": 16000000,
                "runtime": 12000,
            },
            area="file:///geometry.fits",
            output_dir="/direction_setting_split_4",
            query="file://query.txt",
            datasize=616619872,
            comps="TQU",
            wafers=None,
            bands="f090",
            nmat="corr",
            max_dets=None,
            site="act",
            downsample=1,
            maxiter=100,
            tiled=1,
            chunk_nobs=1,
            chunk_duration=None,
            nsplits=4,
            wafer="ws0",
        ),
    ]

    actual_plan = [
        (
            Workflow(
                name="ml_mapmaking_workflow",
                executable="so-site-pipeline",
                context="file:///context.yaml",
                subcommand="make-ml-map",
                id=1,
                environment={},
                resources={
                    "ranks": 896,
                    "threads": 8,
                    "memory": 64000000,
                    "runtime": 12000,
                },
                area="file:///geometry.fits",
                output_dir="/output",
                query="file://obslist_balanced.txt",
                datasize=5230991388,
                comps="TQU",
                wafers=None,
                bands="f090",
                nmat="corr",
                max_dets=None,
                site="act",
                downsample=1,
                maxiter=100,
                tiled=1,
                wafer="ws0",
            ),
            range(0, 7168),
            64000000,
            0,
            13200.000000000002,
        ),
        (
            Workflow(
                name="mission_split_1_null_test_workflow",
                executable="so-site-pipeline",
                context="file:///context.yaml",
                subcommand="make-ml-map",
                id=2,
                environment={},
                resources={
                    "ranks": 224,
                    "threads": 8,
                    "memory": 16000000,
                    "runtime": 12000,
                },
                area="file:///geometry.fits",
                output_dir="/mission_split_1",
                query="file://query.txt",
                datasize=1311130012,
                comps="TQU",
                wafers=None,
                bands="f090",
                nmat="corr",
                max_dets=None,
                site="act",
                downsample=1,
                maxiter=100,
                tiled=1,
                chunk_nobs=1,
                chunk_duration=None,
                nsplits=4,
                wafer="ws0",
            ),
            range(0, 1792),
            16000000,
            13200,
            26400.0,
        ),
        (
            Workflow(
                name="mission_split_2_null_test_workflow",
                executable="so-site-pipeline",
                context="file:///context.yaml",
                subcommand="make-ml-map",
                id=3,
                environment={},
                resources={
                    "ranks": 224,
                    "threads": 8,
                    "memory": 16000000,
                    "runtime": 12000,
                },
                area="file:///geometry.fits",
                output_dir="/mission_split_2",
                query="file://query.txt",
                datasize=1307133118,
                comps="TQU",
                wafers=None,
                bands="f090",
                nmat="corr",
                max_dets=None,
                site="act",
                downsample=1,
                maxiter=100,
                tiled=1,
                chunk_nobs=1,
                chunk_duration=None,
                nsplits=4,
                wafer="ws0",
            ),
            range(0, 1792),
            16000000,
            26400,
            39600.0,
        ),
        (
            Workflow(
                name="mission_split_3_null_test_workflow",
                executable="so-site-pipeline",
                context="file:///context.yaml",
                subcommand="make-ml-map",
                id=4,
                environment={},
                resources={
                    "ranks": 224,
                    "threads": 8,
                    "memory": 16000000,
                    "runtime": 12000,
                },
                area="file:///geometry.fits",
                output_dir="/mission_split_3",
                query="file://query.txt",
                datasize=1305106812,
                comps="TQU",
                wafers=None,
                bands="f090",
                nmat="corr",
                max_dets=None,
                site="act",
                downsample=1,
                maxiter=100,
                tiled=1,
                chunk_nobs=1,
                chunk_duration=None,
                nsplits=4,
                wafer="ws0",
            ),
            range(0, 1792),
            16000000,
            39600,
            52800.0,
        ),
        (
            Workflow(
                name="mission_split_4_null_test_workflow",
                executable="so-site-pipeline",
                context="file:///context.yaml",
                subcommand="make-ml-map",
                id=5,
                environment={},
                resources={
                    "ranks": 224,
                    "threads": 8,
                    "memory": 16000000,
                    "runtime": 12000,
                },
                area="file:///geometry.fits",
                output_dir="/mission_split_4",
                query="file://query.txt",
                datasize=1307621446,
                comps="TQU",
                wafers=None,
                bands="f090",
                nmat="corr",
                max_dets=None,
                site="act",
                downsample=1,
                maxiter=100,
                tiled=1,
                chunk_nobs=1,
                chunk_duration=None,
                nsplits=4,
                wafer="ws0",
            ),
            range(0, 1792),
            16000000,
            52800,
            66000.0,
        ),
        (
            Workflow(
                name="wafer_ws0_split_1_null_test_workflow",
                executable="so-site-pipeline",
                context="file:///context.yaml",
                subcommand="make-ml-map",
                id=6,
                environment={},
                resources={
                    "ranks": 224,
                    "threads": 8,
                    "memory": 16000000,
                    "runtime": 12000,
                },
                area="file:///geometry.fits",
                output_dir="/wafer_ws0_split_1",
                query="file://query.txt",
                datasize=1311130012,
                comps="TQU",
                wafers=None,
                bands="f090",
                nmat="corr",
                max_dets=None,
                site="act",
                downsample=1,
                maxiter=100,
                tiled=1,
                chunk_nobs=1,
                chunk_duration=None,
                nsplits=4,
                wafer="ws0",
            ),
            range(0, 1792),
            16000000,
            66000,
            79200.0,
        ),
        (
            Workflow(
                name="wafer_ws0_split_2_null_test_workflow",
                executable="so-site-pipeline",
                context="file:///context.yaml",
                subcommand="make-ml-map",
                id=7,
                environment={},
                resources={
                    "ranks": 224,
                    "threads": 8,
                    "memory": 16000000,
                    "runtime": 12000,
                },
                area="file:///geometry.fits",
                output_dir="/wafer_ws0_split_2",
                query="file://query.txt",
                datasize=1307133118,
                comps="TQU",
                wafers=None,
                bands="f090",
                nmat="corr",
                max_dets=None,
                site="act",
                downsample=1,
                maxiter=100,
                tiled=1,
                chunk_nobs=1,
                chunk_duration=None,
                nsplits=4,
                wafer="ws0",
            ),
            range(0, 1792),
            16000000,
            79200,
            92400.0,
        ),
        (
            Workflow(
                name="wafer_ws0_split_3_null_test_workflow",
                executable="so-site-pipeline",
                context="file:///context.yaml",
                subcommand="make-ml-map",
                id=8,
                environment={},
                resources={
                    "ranks": 224,
                    "threads": 8,
                    "memory": 16000000,
                    "runtime": 12000,
                },
                area="file:///geometry.fits",
                output_dir="/wafer_ws0_split_3",
                query="file://query.txt",
                datasize=1305106812,
                comps="TQU",
                wafers=None,
                bands="f090",
                nmat="corr",
                max_dets=None,
                site="act",
                downsample=1,
                maxiter=100,
                tiled=1,
                chunk_nobs=1,
                chunk_duration=None,
                nsplits=4,
                wafer="ws0",
            ),
            range(0, 1792),
            16000000,
            92400,
            105600.0,
        ),
        (
            Workflow(
                name="wafer_ws0_split_4_null_test_workflow",
                executable="so-site-pipeline",
                context="file:///context.yaml",
                subcommand="make-ml-map",
                id=9,
                environment={},
                resources={
                    "ranks": 224,
                    "threads": 8,
                    "memory": 16000000,
                    "runtime": 12000,
                },
                area="file:///geometry.fits",
                output_dir="/wafer_ws0_split_4",
                query="file://query.txt",
                datasize=1307621446,
                comps="TQU",
                wafers=None,
                bands="f090",
                nmat="corr",
                max_dets=None,
                site="act",
                downsample=1,
                maxiter=100,
                tiled=1,
                chunk_nobs=1,
                chunk_duration=None,
                nsplits=4,
                wafer="ws0",
            ),
            range(0, 1792),
            16000000,
            105600,
            118800.0,
        ),
        (
            Workflow(
                name="direction_rising_split_1_null_test_workflow",
                executable="so-site-pipeline",
                context="file:///context.yaml",
                subcommand="make-ml-map",
                id=10,
                environment={},
                resources={
                    "ranks": 224,
                    "threads": 8,
                    "memory": 16000000,
                    "runtime": 12000,
                },
                area="file:///geometry.fits",
                output_dir="/direction_rising_split_1",
                query="file://query.txt",
                datasize=691266434,
                comps="TQU",
                wafers=None,
                bands="f090",
                nmat="corr",
                max_dets=None,
                site="act",
                downsample=1,
                maxiter=100,
                tiled=1,
                chunk_nobs=1,
                chunk_duration=None,
                nsplits=4,
                wafer="ws0",
            ),
            range(0, 1792),
            16000000,
            118800,
            132000.0,
        ),
        (
            Workflow(
                name="direction_rising_split_2_null_test_workflow",
                executable="so-site-pipeline",
                context="file:///context.yaml",
                subcommand="make-ml-map",
                id=11,
                environment={},
                resources={
                    "ranks": 224,
                    "threads": 8,
                    "memory": 16000000,
                    "runtime": 12000,
                },
                area="file:///geometry.fits",
                output_dir="/direction_rising_split_2",
                query="file://query.txt",
                datasize=689067348,
                comps="TQU",
                wafers=None,
                bands="f090",
                nmat="corr",
                max_dets=None,
                site="act",
                downsample=1,
                maxiter=100,
                tiled=1,
                chunk_nobs=1,
                chunk_duration=None,
                nsplits=4,
                wafer="ws0",
            ),
            range(0, 1792),
            16000000,
            132000,
            145200.0,
        ),
        (
            Workflow(
                name="direction_rising_split_3_null_test_workflow",
                executable="so-site-pipeline",
                context="file:///context.yaml",
                subcommand="make-ml-map",
                id=12,
                environment={},
                resources={
                    "ranks": 224,
                    "threads": 8,
                    "memory": 16000000,
                    "runtime": 12000,
                },
                area="file:///geometry.fits",
                output_dir="/direction_rising_split_3",
                query="file://query.txt",
                datasize=689196634,
                comps="TQU",
                wafers=None,
                bands="f090",
                nmat="corr",
                max_dets=None,
                site="act",
                downsample=1,
                maxiter=100,
                tiled=1,
                chunk_nobs=1,
                chunk_duration=None,
                nsplits=4,
                wafer="ws0",
            ),
            range(0, 1792),
            16000000,
            145200,
            158400.0,
        ),
        (
            Workflow(
                name="direction_rising_split_4_null_test_workflow",
                executable="so-site-pipeline",
                context="file:///context.yaml",
                subcommand="make-ml-map",
                id=13,
                environment={},
                resources={
                    "ranks": 224,
                    "threads": 8,
                    "memory": 16000000,
                    "runtime": 12000,
                },
                area="file:///geometry.fits",
                output_dir="/direction_rising_split_4",
                query="file://query.txt",
                datasize=689290508,
                comps="TQU",
                wafers=None,
                bands="f090",
                nmat="corr",
                max_dets=None,
                site="act",
                downsample=1,
                maxiter=100,
                tiled=1,
                chunk_nobs=1,
                chunk_duration=None,
                nsplits=4,
                wafer="ws0",
            ),
            range(0, 1792),
            16000000,
            158400,
            171600.0,
        ),
        (
            Workflow(
                name="direction_setting_split_1_null_test_workflow",
                executable="so-site-pipeline",
                context="file:///context.yaml",
                subcommand="make-ml-map",
                id=14,
                environment={},
                resources={
                    "ranks": 224,
                    "threads": 8,
                    "memory": 16000000,
                    "runtime": 12000,
                },
                area="file:///geometry.fits",
                output_dir="/direction_setting_split_1",
                query="file://query.txt",
                datasize=615677782,
                comps="TQU",
                wafers=None,
                bands="f090",
                nmat="corr",
                max_dets=None,
                site="act",
                downsample=1,
                maxiter=100,
                tiled=1,
                chunk_nobs=1,
                chunk_duration=None,
                nsplits=4,
                wafer="ws0",
            ),
            range(0, 1792),
            16000000,
            171600,
            184800.0,
        ),
        (
            Workflow(
                name="direction_setting_split_2_null_test_workflow",
                executable="so-site-pipeline",
                context="file:///context.yaml",
                subcommand="make-ml-map",
                id=15,
                environment={},
                resources={
                    "ranks": 224,
                    "threads": 8,
                    "memory": 16000000,
                    "runtime": 12000,
                },
                area="file:///geometry.fits",
                output_dir="/direction_setting_split_2",
                query="file://query.txt",
                datasize=621404494,
                comps="TQU",
                wafers=None,
                bands="f090",
                nmat="corr",
                max_dets=None,
                site="act",
                downsample=1,
                maxiter=100,
                tiled=1,
                chunk_nobs=1,
                chunk_duration=None,
                nsplits=4,
                wafer="ws0",
            ),
            range(0, 1792),
            16000000,
            184800,
            198000.0,
        ),
        (
            Workflow(
                name="direction_setting_split_3_null_test_workflow",
                executable="so-site-pipeline",
                context="file:///context.yaml",
                subcommand="make-ml-map",
                id=16,
                environment={},
                resources={
                    "ranks": 224,
                    "threads": 8,
                    "memory": 16000000,
                    "runtime": 12000,
                },
                area="file:///geometry.fits",
                output_dir="/direction_setting_split_3",
                query="file://query.txt",
                datasize=618468316,
                comps="TQU",
                wafers=None,
                bands="f090",
                nmat="corr",
                max_dets=None,
                site="act",
                downsample=1,
                maxiter=100,
                tiled=1,
                chunk_nobs=1,
                chunk_duration=None,
                nsplits=4,
                wafer="ws0",
            ),
            range(0, 1792),
            16000000,
            198000,
            211200.0,
        ),
        (
            Workflow(
                name="direction_setting_split_4_null_test_workflow",
                executable="so-site-pipeline",
                context="file:///context.yaml",
                subcommand="make-ml-map",
                id=17,
                environment={},
                resources={
                    "ranks": 224,
                    "threads": 8,
                    "memory": 16000000,
                    "runtime": 12000,
                },
                area="file:///geometry.fits",
                output_dir="/direction_setting_split_4",
                query="file://query.txt",
                datasize=616619872,
                comps="TQU",
                wafers=None,
                bands="f090",
                nmat="corr",
                max_dets=None,
                site="act",
                downsample=1,
                maxiter=100,
                tiled=1,
                chunk_nobs=1,
                chunk_duration=None,
                nsplits=4,
                wafer="ws0",
            ),
            range(0, 1792),
            16000000,
            211200,
            224400.0,
        ),
    ]

    planner = HeftPlanner(None, None, None)
    planner._logger = ru.Logger("dummy")
    planner._est_memory = list()

    planner._resource_requirements = {
        1: {
            "req_cpus": 7168,
            "req_memory": 64000000,
            "req_walltime": 13200.000000000002,
        },
        2: {
            "req_cpus": 1792,
            "req_memory": 16000000,
            "req_walltime": 13200.000000000002,
        },
        3: {
            "req_cpus": 1792,
            "req_memory": 16000000,
            "req_walltime": 13200.000000000002,
        },
        4: {
            "req_cpus": 1792,
            "req_memory": 16000000,
            "req_walltime": 13200.000000000002,
        },
        5: {
            "req_cpus": 1792,
            "req_memory": 16000000,
            "req_walltime": 13200.000000000002,
        },
        6: {
            "req_cpus": 1792,
            "req_memory": 16000000,
            "req_walltime": 13200.000000000002,
        },
        7: {
            "req_cpus": 1792,
            "req_memory": 16000000,
            "req_walltime": 13200.000000000002,
        },
        8: {
            "req_cpus": 1792,
            "req_memory": 16000000,
            "req_walltime": 13200.000000000002,
        },
        9: {
            "req_cpus": 1792,
            "req_memory": 16000000,
            "req_walltime": 13200.000000000002,
        },
        10: {
            "req_cpus": 1792,
            "req_memory": 16000000,
            "req_walltime": 13200.000000000002,
        },
        11: {
            "req_cpus": 1792,
            "req_memory": 16000000,
            "req_walltime": 13200.000000000002,
        },
        12: {
            "req_cpus": 1792,
            "req_memory": 16000000,
            "req_walltime": 13200.000000000002,
        },
        13: {
            "req_cpus": 1792,
            "req_memory": 16000000,
            "req_walltime": 13200.000000000002,
        },
        14: {
            "req_cpus": 1792,
            "req_memory": 16000000,
            "req_walltime": 13200.000000000002,
        },
        15: {
            "req_cpus": 1792,
            "req_memory": 16000000,
            "req_walltime": 13200.000000000002,
        },
        16: {
            "req_cpus": 1792,
            "req_memory": 16000000,
            "req_walltime": 13200.000000000002,
        },
        17: {
            "req_cpus": 1792,
            "req_memory": 16000000,
            "req_walltime": 13200.000000000002,
        },
    }

    planner._campaign = workflows
    planner._resources = Resource(
        name="tiger3",
        nodes=64,
        cores_per_node=112,
        memory_per_node=humanfriendly.parse_size("1TB") // 1000000,  # in MB
        default_queue="normal",
        maximum_walltime=3600000,  # in minutes
    )

    est_plan, _ = planner.plan()
    assert actual_plan == est_plan
