[slurmise]
base_dir = '/scratch/gpfs/SIMONSOBS/users/ip8725/act_test/slurmise_dir'

[slurmise.job.make-ml-map]
mutlistep = true
job_spec = '--cpu_bind=cores --export=ALL --ntasks-per-node={cpus:numeric} --cpus-per-task=8 so-site-pipeline make-ml-map {query:category} {footprint:file} {output_folder:ignore} --bands={bands:category} --comps={maps:category} --context={context:file} --maxiter={iters:numeric} --site={site:category} --tiled=1 --wafer={wafer:category}'
job_prefix = "srun"
file_parsers.footprint = "file_md5"
file_parsers.context = "file_md5"
default_mem = 300000
default_time = 80
