# Example configuration for DirectionNullTestWorkflow
# 
# This configuration demonstrates how to use the new direction-based
# null test workflow that splits observations by scan direction 
# (rising, setting, middle) with nsplits=2 time-interleaved splits.

[campaign]
deadline = "2d"
resources = { nodes = 4, cores-per-node = 112 }

[campaign.ml-null-tests.direction-tests]
# Direction-based null test configuration
context = "context.yaml"
area = "so_geometry_v20250306_lat_f090.fits"
output_dir = "output/direction_null_tests"
query = "obs_id IN ('obs1', 'obs2', 'obs3', 'obs4', 'obs5', 'obs6')"

# Basic mapmaking parameters
bands = "f090"
wafer = "ws0"
comps = "TQU"
maxiter = 10
tiled = 1
site = "act"

# Direction test specific parameters
chunk_nobs = 3      # Number of chunks to create per direction
nsplits = 2         # Fixed to 2 as specified in the issue

# Resource allocation
[campaign.ml-null-tests.direction-tests.resources]
ranks = 4
threads = 8
memory = "80000"
runtime = "80000"

# Environment variables
[campaign.ml-null-tests.direction-tests.environment]
DOT_MOBY2 = "act_dot_moby2"
SOTODLIB_SITECONFIG = "site.yaml"

# This configuration will create workflows with output directories like:
# - output/direction_null_tests/direction_rising_split_1
# - output/direction_null_tests/direction_rising_split_2
# - output/direction_null_tests/direction_setting_split_1
# - output/direction_null_tests/direction_setting_split_2
# - output/direction_null_tests/direction_middle_split_1
# - output/direction_null_tests/direction_middle_split_2