name: Tests
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@v7
      - run: |
             uv sync --group dev
             uv run pytest -vvv tests/ --cov=so_campaign_manager
      - name: Install coverage
        run: uv pip install coverage
      - name: Upload coverage report
        run: uv run coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
