name: Tests
permissions:
  contents: read
  pull-requests: write

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - run: |
             pip install https://github.com/simonsobs/sotodlib/archive/master.tar.gz
             pip install -e ".[dev]"
             pytest -vvv tests/ --cov --cov-append
      - uses: coverallsapp/github-action@v2
        with:
          file: .coverage