name: Tests

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - run: pip install -e ".[dev]"
      - run: pytest -vvv tests/ --cov --cov-append
      - uses: coverallsapp/github-action@v2
        with:
          file: .coverage